/*
 * Generated from schema.json by scripts/generate-types.ts.
 * Do not edit this file manually.
 */

/**
 * Validates a single JSONL line: either a header (line 1) or an event (lines 2+). Top-level oneOf chooses header vs entry; per-event-type payload shapes are enforced via the events subschemas.
 */
export type AgentTrailV010 = TrailEnvelope | Header | Entry;
/**
 * Unique within the file. Globally-unique recommended (ULID/UUID) so cross-segment reconciliation can dedup by id. 8+ chars hex or alphanumeric recommended.
 */
export type Id = string;
/**
 * Writer timestamp: UTC ISO-8601 with millisecond precision
 */
export type Iso8601 = string;
/**
 * SHA-256 hash as lowercase hex (64 chars)
 */
export type Sha256Hex = string;
export type AgentName =
  | (
      | "claude-code"
      | "pi"
      | "openclaw"
      | "codex-cli"
      | "cursor"
      | "opencode"
      | "aider"
      | "amp"
      | "cline"
      | "crush"
      | "kimi-code"
      | "qwen-code"
      | "factory"
      | "vibe"
      | "copilot-cli"
      | "copilot-chat"
      | "chatgpt"
      | "clawdbot"
    )
  | string;
/**
 * Multi-segment marker. Absent or {seq:1} for a single-segment trail. Reconciler primitive for daemon resume and multi-file sessions (spec §8.5).
 */
export type Segment =
  | {
      seq: 1;
    }
  | {
      seq: number;
      prev_content_hash: Sha256Hex | null;
    };
export type Entry = EntryBase &
  (
    | UserMessage
    | AgentMessage
    | ToolCall
    | ToolResult
    | SessionSummary
    | SystemEvent
    | AgentThinking
    | UserInterrupt
    | ContextCompact
    | BranchPoint
    | BranchSummary
    | ModelChange
    | SessionTerminated
    | SessionEnd
    | Unknown
  );
export type ToolKind =
  | "file_read"
  | "file_write"
  | "file_edit"
  | "file_search"
  | "shell_command"
  | "shell_output"
  | "mcp_call"
  | "web_fetch"
  | "web_search"
  | "notebook_edit"
  | "task_plan"
  | "subagent_invoke"
  | "other";

/**
 * Optional trail envelope record (line 1). File-level metadata; not part of the event graph. When present, MUST appear at line 1 and the session header MUST follow on line 2. At most one per file.
 */
export interface TrailEnvelope {
  type: "trail";
  schema_version: "0.1.0";
  id: Id;
  name?: string;
  description?: string;
  ts: Iso8601;
  producer: string;
  content_hash?: Sha256Hex | "<pending>";
  tags?: string[];
  vcs?: Vcs;
  fork_from?: {
    trail_id: string;
    content_hash?: Sha256Hex;
  };
  redacted_from?: {
    content_hash: Sha256Hex;
  };
  /**
   * Optional manifest of sessions contained in the file. Validator warns on drift vs actual file content.
   */
  sessions?: {
    id: Id;
    agent: AgentName;
    role?: string;
    follows?: string;
  }[];
  /**
   * Free-form vendor extensions. Recommended keys use a reverse-domain or x-<adapter>/ namespace.
   */
  meta?: {
    [k: string]: unknown;
  };
}
export interface Vcs {
  type: "git" | "jj" | "hg" | "svn";
  revision: string;
  /**
   * Canonical remote URL for the working tree. Adapters MUST normalize before emission: strip embedded credentials, strip trailing .git for git URLs, and normalize SSH/HTTPS variants to a single canonical form (https://host/path).
   */
  remote_url?: string;
}
/**
 * Session header. Required at line 1, or at line 2 when a trail envelope occupies line 1. Not part of the event graph.
 */
export interface Header {
  type: "session";
  schema_version: "0.1.0";
  id: Id;
  /**
   * Globally-unique source-session identifier. Stable across all segments of one source session (spec §8.5). Reconcilers group segments by session_uid. Optional in v0.1 single-segment trails; writers SHOULD emit it for forward-compat. Required by spec when segment.seq > 1; schema does not yet enforce that pairing (reconciler PR closes the gap). ULID is recommended (lexicographic tie-breaker); UUID accepted.
   */
  session_uid?: string;
  segment?: Segment;
  content_hash?: Sha256Hex | "<pending>";
  ts: Iso8601;
  /**
   * Live-capture marker. Present means writer is actively appending or last appended in streaming mode. Absent means non-streaming or unaware writer.
   */
  stream?: {
    state: "open" | "closed";
    started_at?: Iso8601;
  };
  agent: {
    name: AgentName;
    version?: string;
    model_default?: string;
  };
  cwd?: string;
  vcs?: Vcs;
  fork_from?: {
    session_id: string;
    content_hash?: Sha256Hex;
    entry_id?: string;
  };
  redacted_from?: {
    content_hash: Sha256Hex;
  };
  source?: {
    agent?: AgentName;
    path?: string;
    format_version?: string;
  };
  /**
   * Vendor extensions with reverse-domain keys (e.g., com.example.field)
   */
  metadata?: {
    [k: string]: unknown;
  };
  /**
   * Free-form vendor extensions. Recommended keys use a reverse-domain or x-<adapter>/ namespace.
   */
  meta?: {
    [k: string]: unknown;
  };
}
export interface EntryBase {
  type: string;
  id: Id;
  parent_id?: Id | null;
  ts: Iso8601;
  payload: {
    [k: string]: unknown;
  };
  semantic?: SemanticMetadata;
  source?: SourceMetadata;
  metadata?: {
    [k: string]: unknown;
  };
}
/**
 * Semantic linking for cross-event references when explicit IDs are unreliable.
 */
export interface SemanticMetadata {
  group_id?: string;
  call_id?: string;
  tool_kind?: ToolKind;
}
/**
 * Adapter-provided metadata about the source event.
 */
export interface SourceMetadata {
  agent?: AgentName;
  original_type?: string;
  schema_version?: string;
  /**
   * Opaque source object preserved verbatim. If an object, may use envelope_ref to reference an earlier entry's inlined envelope.
   */
  raw?: {
    [k: string]: unknown;
  };
  synthesized?: boolean;
}
export interface UserMessage {
  type?: "user_message";
  payload?: {
    text: string;
    attachments?: {
      kind: "image" | "file" | "other";
      media_type?: string;
      uri?: string;
      name?: string;
    }[];
  };
  [k: string]: unknown;
}
export interface AgentMessage {
  type?: "agent_message";
  payload?: {
    text: string;
    model?: string;
    stop_reason?: string;
    usage?: AgentMessageUsage;
  };
  [k: string]: unknown;
}
/**
 * Token usage for this agent_message. input_tokens/output_tokens are deltas for this message; *_cumulative variants are running totals through this point. cache_read_tokens and cache_creation_tokens are independent billing categories (Anthropic and OpenAI Responses API semantics): input_tokens counts non-cached input only and total billed input = input_tokens + cache_read_tokens + cache_creation_tokens. Required-when-present field presence is enforced semantically by the validator.
 */
export interface AgentMessageUsage {
  input_tokens?: number;
  output_tokens?: number;
  input_tokens_cumulative?: number;
  output_tokens_cumulative?: number;
  cache_read_tokens?: number;
  cache_creation_tokens?: number;
  reasoning_tokens?: number;
}
export interface ToolCall {
  type?: "tool_call";
  payload?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ToolResult {
  type?: "tool_result";
  payload?: {
    for_id?: Id;
    ok: boolean;
    output?: string;
    truncated?: boolean;
    overflow_ref?: string | null;
    error?: string | null;
  };
  [k: string]: unknown;
}
export interface SessionSummary {
  type?: "session_summary";
  payload?: {
    scope: "session";
    text: string;
    model?: string;
  };
  [k: string]: unknown;
}
export interface SystemEvent {
  type?: "system_event";
  payload?: {
    kind: string;
    text?: string;
    data?: {
      [k: string]: unknown;
    };
  };
  [k: string]: unknown;
}
export interface AgentThinking {
  type?: "agent_thinking";
  payload?: {
    text: string;
    model?: string;
    level?: "low" | "medium" | "high" | "xhigh";
  };
  [k: string]: unknown;
}
export interface UserInterrupt {
  type?: "user_interrupt";
  payload?: {
    reason?: string;
  };
  [k: string]: unknown;
}
export interface ContextCompact {
  type?: "context_compact";
  payload?: {
    summary: string;
    trigger?: "manual" | "auto";
    tokens_before?: number;
    tokens_after?: number;
  };
  [k: string]: unknown;
}
export interface BranchPoint {
  type?: "branch_point";
  payload?: {
    from_id: Id;
    reason?: string;
  };
  [k: string]: unknown;
}
export interface BranchSummary {
  type?: "branch_summary";
  payload?: {
    abandoned_branch_id: Id;
    summary: string;
    model?: string;
  };
  [k: string]: unknown;
}
export interface ModelChange {
  type?: "model_change";
  payload?: {
    from_model?: string;
    to_model: string;
  };
  [k: string]: unknown;
}
export interface SessionTerminated {
  type?: "session_terminated";
  payload?: {
    reason: "eof_with_open_tool_calls" | "process_terminated" | "truncated" | "user_abort";
    open_call_ids?: Id[];
  };
  [k: string]: unknown;
}
export interface SessionEnd {
  type?: "session_end";
  payload?: {
    reason: "complete" | "user_quit" | "agent_idle";
    final_message_id?: Id;
  };
  [k: string]: unknown;
}
/**
 * Catch-all for unrecognized event types. Readers must tolerate these.
 */
export interface Unknown {
  type?: string;
  payload?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
