/*
 * Generated from schema.json by scripts/generate-types.ts.
 * Do not edit this file manually.
 */

/**
 * Validates a single JSONL line: either a header (line 1) or an event (lines 2+). Top-level oneOf chooses header vs entry; per-event-type payload shapes are enforced via the events subschemas.
 */
export type AgentTrailV010 = Header | Entry;
/**
 * Unique within the file. 8+ chars hex or alphanumeric recommended.
 */
export type Id = string;
/**
 * SHA-256 hash as lowercase hex (64 chars)
 */
export type Sha256Hex = string;
/**
 * Writer timestamp: UTC ISO-8601 with millisecond precision
 */
export type Iso8601 = string;
export type AgentName =
  | (
      | "claude-code"
      | "pi"
      | "openclaw"
      | "codex-cli"
      | "cursor"
      | "opencode"
      | "aider"
      | "amp"
      | "cline"
      | "crush"
      | "kimi-code"
      | "qwen-code"
      | "factory"
      | "vibe"
      | "copilot-cli"
      | "copilot-chat"
      | "chatgpt"
      | "clawdbot"
    )
  | string;
export type Entry = EntryBase &
  (
    | UserMessage
    | AgentMessage
    | ToolCall
    | ToolResult
    | SessionSummary
    | SystemEvent
    | AgentThinking
    | UserInterrupt
    | ContextCompact
    | BranchPoint
    | BranchSummary
    | ModelChange
    | SessionTerminated
    | Unknown
  );
export type ToolKind =
  | "file_read"
  | "file_write"
  | "file_edit"
  | "file_search"
  | "shell_command"
  | "shell_output"
  | "mcp_call"
  | "web_fetch"
  | "web_search"
  | "notebook_edit"
  | "task_plan"
  | "subagent_invoke"
  | "other";

/**
 * Session header (line 1). Not part of the event graph.
 */
export interface Header {
  type: "session";
  schema_version: "0.1.0";
  id: Id;
  content_hash?: Sha256Hex | "<pending>";
  ts: Iso8601;
  agent: {
    name: AgentName;
    version?: string;
    model_default?: string;
  };
  cwd?: string;
  vcs?: Vcs;
  fork_from?: {
    session_id: string;
    content_hash?: Sha256Hex;
    entry_id?: string;
  };
  redacted_from?: {
    content_hash: Sha256Hex;
  };
  source?: {
    agent?: AgentName;
    path?: string;
    format_version?: string;
  };
  /**
   * Vendor extensions with reverse-domain keys (e.g., com.example.field)
   */
  metadata?: {
    [k: string]: unknown;
  };
}
export interface Vcs {
  type: "git" | "jj" | "hg" | "svn";
  revision: string;
}
export interface EntryBase {
  type: string;
  id: Id;
  parent_id?: Id | null;
  ts: Iso8601;
  payload: {
    [k: string]: unknown;
  };
  semantic?: SemanticMetadata;
  source?: SourceMetadata;
  metadata?: {
    [k: string]: unknown;
  };
}
/**
 * Semantic linking for cross-event references when explicit IDs are unreliable.
 */
export interface SemanticMetadata {
  group_id?: string;
  call_id?: string;
  tool_kind?: ToolKind;
}
/**
 * Adapter-provided metadata about the source event.
 */
export interface SourceMetadata {
  agent?: AgentName;
  original_type?: string;
  schema_version?: string;
  /**
   * Opaque source object preserved verbatim
   */
  raw?: {
    [k: string]: unknown;
  };
  synthesized?: boolean;
}
export interface UserMessage {
  type?: "user_message";
  payload?: {
    text: string;
    attachments?: {
      kind: "image" | "file" | "other";
      media_type?: string;
      uri?: string;
      name?: string;
    }[];
  };
  [k: string]: unknown;
}
export interface AgentMessage {
  type?: "agent_message";
  payload?: {
    text: string;
    model?: string;
    stop_reason?: string;
  };
  [k: string]: unknown;
}
export interface ToolCall {
  type?: "tool_call";
  payload?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ToolResult {
  type?: "tool_result";
  payload?: {
    for_id?: Id;
    ok: boolean;
    output?: string;
    truncated?: boolean;
    overflow_ref?: string | null;
    error?: string | null;
  };
  [k: string]: unknown;
}
export interface SessionSummary {
  type?: "session_summary";
  payload?: {
    scope: "session";
    text: string;
    model?: string;
  };
  [k: string]: unknown;
}
export interface SystemEvent {
  type?: "system_event";
  payload?: {
    kind: string;
    text?: string;
    data?: {
      [k: string]: unknown;
    };
  };
  [k: string]: unknown;
}
export interface AgentThinking {
  type?: "agent_thinking";
  payload?: {
    text: string;
    model?: string;
    level?: "low" | "medium" | "high" | "xhigh";
  };
  [k: string]: unknown;
}
export interface UserInterrupt {
  type?: "user_interrupt";
  payload?: {
    reason?: string;
  };
  [k: string]: unknown;
}
export interface ContextCompact {
  type?: "context_compact";
  payload?: {
    summary: string;
    trigger?: "manual" | "auto";
    tokens_before?: number;
    tokens_after?: number;
  };
  [k: string]: unknown;
}
export interface BranchPoint {
  type?: "branch_point";
  payload?: {
    from_id: Id;
    reason?: string;
  };
  [k: string]: unknown;
}
export interface BranchSummary {
  type?: "branch_summary";
  payload?: {
    abandoned_branch_id: Id;
    summary: string;
    model?: string;
  };
  [k: string]: unknown;
}
export interface ModelChange {
  type?: "model_change";
  payload?: {
    from_model?: string;
    to_model: string;
  };
  [k: string]: unknown;
}
export interface SessionTerminated {
  type?: "session_terminated";
  payload?: {
    reason: "eof_with_open_tool_calls" | "process_terminated" | "truncated" | "user_abort";
    open_call_ids?: Id[];
  };
  [k: string]: unknown;
}
/**
 * Catch-all for unrecognized event types. Readers must tolerate these.
 */
export interface Unknown {
  type?: string;
  payload?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
