/*
 * Generated from schema.json by scripts/generate-types.ts.
 * Do not edit this file manually.
 */

/**
 * Validates a single JSONL line: either a header (line 1) or an event (lines 2+). Top-level oneOf chooses header vs entry; per-event-type payload shapes are enforced via the events subschemas.
 */
export type AgentTrailV010 = TrailEnvelope | Header | Entry;
/**
 * Writer timestamp: UTC ISO-8601 with millisecond precision
 */
export type Iso8601 = string;
/**
 * SHA-256 hash as lowercase hex (64 chars)
 */
export type Sha256Hex = string;
export type AgentName =
  | (
      | "claude-code"
      | "pi"
      | "openclaw"
      | "codex-cli"
      | "cursor"
      | "opencode"
      | "aider"
      | "amp"
      | "cline"
      | "crush"
      | "kimi-code"
      | "qwen-code"
      | "factory"
      | "vibe"
      | "copilot-cli"
      | "copilot-chat"
      | "chatgpt"
      | "clawdbot"
    )
  | string;
/**
 * Session header. The first session header is required at line 1, or at line 2 when a trail envelope occupies line 1. Multi-session files (spec §8.6) carry additional session headers later in the file; each opens a new (header, events*) group. Not part of the event graph.
 */
export type Header = {
  [k: string]: unknown;
} & {
  type: "session";
  schema_version: "0.1.0";
  /**
   * Globally-unique identifier shape: ULID (26 Crockford base32 chars, case-insensitive), hyphenated UUID (36 chars), or unhyphenated UUID (32 hex chars). Header ids, event ids, and envelope ids share this shape so cross-segment reconciliation can dedup by id (spec §8.5).
   */
  id: string;
  /**
   * Globally-unique source-session identifier. Stable across all segments of one source session (spec §8.5). Reconcilers group segments by session_uid. Optional in v0.1 single-segment trails; writers SHOULD emit it for forward-compat. Required (and enforced by the header allOf if/then) when segment.seq > 1. ULID is recommended (lexicographic tie-breaker); UUID accepted.
   */
  session_uid?: string;
  segment?: Segment;
  content_hash?: Sha256Hex | "<pending>";
  ts: Iso8601;
  /**
   * Live-capture marker. Present means writer is actively appending or last appended in streaming mode. Absent means non-streaming or unaware writer.
   */
  stream?: {
    state: "open" | "closed";
    started_at?: Iso8601;
  };
  agent: {
    name: AgentName;
    version?: string;
    model_default?: string;
  };
  cwd?: string;
  vcs?: Vcs;
  fork_from?: {
    session_id: string;
    content_hash?: Sha256Hex;
    entry_id?: string;
  };
  redacted_from?: {
    content_hash: Sha256Hex;
  };
  source?: {
    agent?: AgentName;
    path?: string;
    format_version?: string;
  };
  /**
   * Free-form vendor extensions. Recommended keys use a reverse-domain or x-<adapter>/ namespace (spec §8.0.3).
   */
  meta?: {
    [k: string]: unknown;
  };
};
/**
 * Multi-segment marker. Absent or {seq:1} for a single-segment trail. Reconciler primitive for daemon resume and multi-file sessions (spec §8.5).
 */
export type Segment =
  | {
      seq: 1;
    }
  | {
      seq: number;
      prev_content_hash: Sha256Hex | null;
    };
export type Entry = EntryBase &
  (
    | UserMessage
    | AgentMessage
    | ToolCall
    | ToolResult
    | SessionSummary
    | SystemEvent
    | AgentThinking
    | UserInterrupt
    | ContextCompact
    | BranchPoint
    | BranchSummary
    | ModelChange
    | SessionTerminated
    | SessionEnd
    | CommandInvoke
    | Unknown
  );
export type ToolKind =
  | "file_read"
  | "file_write"
  | "file_edit"
  | "file_search"
  | "shell_command"
  | "shell_output"
  | "mcp_call"
  | "web_fetch"
  | "web_search"
  | "notebook_edit"
  | "task_plan"
  | "subagent_invoke"
  | "other";

/**
 * Optional trail envelope record (line 1). File-level metadata; not part of the event graph. When present, MUST appear at line 1 and the first session header MUST follow on line 2. At most one per file. Multi-session files (spec §8.6) carry one envelope followed by N session groups in file order.
 */
export interface TrailEnvelope {
  type: "trail";
  schema_version: "0.1.0";
  /**
   * Globally-unique identifier shape: ULID (26 Crockford base32 chars, case-insensitive), hyphenated UUID (36 chars), or unhyphenated UUID (32 hex chars). Header ids, event ids, and envelope ids share this shape so cross-segment reconciliation can dedup by id (spec §8.5).
   */
  id: string;
  name?: string;
  description?: string;
  ts: Iso8601;
  producer: string;
  content_hash?: Sha256Hex | "<pending>";
  tags?: string[];
  vcs?: Vcs;
  fork_from?: {
    trail_id: string;
    content_hash?: Sha256Hex;
  };
  redacted_from?: {
    content_hash: Sha256Hex;
  };
  /**
   * Optional manifest of sessions contained in the file, one entry per session group in file order (spec §8.0.4, §8.6). Validator warns on length mismatch or per-entry drift vs actual file content.
   */
  sessions?: {
    /**
     * Globally-unique identifier shape: ULID (26 Crockford base32 chars, case-insensitive), hyphenated UUID (36 chars), or unhyphenated UUID (32 hex chars). Header ids, event ids, and envelope ids share this shape so cross-segment reconciliation can dedup by id (spec §8.5).
     */
    id: string;
    agent: AgentName;
    role?: string;
    follows?: string;
  }[];
  /**
   * Free-form vendor extensions. Recommended keys use a reverse-domain or x-<adapter>/ namespace.
   */
  meta?: {
    [k: string]: unknown;
  };
}
export interface Vcs {
  type: "git" | "jj" | "hg" | "svn";
  revision: string;
  /**
   * Canonical remote URL for the working tree. Adapters MUST normalize before emission: strip embedded credentials, strip trailing .git for git URLs, and normalize SSH/HTTPS variants to a single canonical form (https://host/path).
   */
  remote_url?: string;
  /**
   * Active branch / bookmark / topic name the session is running on. For git, the short branch name (e.g., `feature/x`). Detached-HEAD sessions MAY omit this field.
   */
  branch?: string;
  /**
   * Commit hash at session start (lowercase hex, 7-64 chars). For git this is typically the same value as `revision`; the field exists as an explicit, version-control-neutral alias and survives across VCS migrations.
   */
  head_commit?: string;
  /**
   * Worktree context when the session ran inside a working-tree clone or worktree (git worktree, jj workspace, etc.).
   */
  worktree?: {
    name: string;
    path: string;
    /**
     * Working directory of the parent repository at the time the worktree was created.
     */
    original_cwd?: string;
    /**
     * Branch the parent repository was on when the worktree was created.
     */
    original_branch?: string;
    /**
     * Commit hash the worktree was forked from.
     */
    original_head_commit?: string;
  };
}
export interface EntryBase {
  type: string;
  /**
   * Globally-unique identifier shape: ULID (26 Crockford base32 chars, case-insensitive), hyphenated UUID (36 chars), or unhyphenated UUID (32 hex chars). Header ids, event ids, and envelope ids share this shape so cross-segment reconciliation can dedup by id (spec §8.5).
   */
  id: string;
  parent_id?: string | null;
  ts: Iso8601;
  payload: {
    [k: string]: unknown;
  };
  semantic?: SemanticMetadata;
  source?: SourceMetadata;
  meta?: {
    [k: string]: unknown;
  };
}
/**
 * Semantic linking for cross-event references when explicit IDs are unreliable.
 */
export interface SemanticMetadata {
  group_id?: string;
  call_id?: string;
  tool_kind?: ToolKind;
}
/**
 * Adapter-provided metadata about the source event.
 */
export interface SourceMetadata {
  agent?: AgentName;
  original_type?: string;
  schema_version?: string;
  /**
   * Opaque source object preserved verbatim. If an object, may use envelope_ref to reference an earlier entry's inlined envelope.
   */
  raw?: {
    [k: string]: unknown;
  };
  synthesized?: boolean;
}
export interface UserMessage {
  type?: "user_message";
  payload?: {
    text: string;
    attachments?: {
      kind: "image" | "file" | "other";
      media_type?: string;
      uri?: string;
      name?: string;
    }[];
  };
  [k: string]: unknown;
}
export interface AgentMessage {
  type?: "agent_message";
  payload?: {
    text: string;
    model?: string;
    stop_reason?: string;
    usage?: AgentMessageUsage;
  };
  [k: string]: unknown;
}
/**
 * Token usage for this agent_message. input_tokens/output_tokens are deltas for this message; *_cumulative variants are running totals through this point. cache_read_tokens and cache_creation_tokens are independent billing categories (Anthropic and OpenAI Responses API semantics): input_tokens counts non-cached input only and total billed input = input_tokens + cache_read_tokens + cache_creation_tokens. Required-when-present field presence is enforced semantically by the validator.
 */
export interface AgentMessageUsage {
  input_tokens?: number;
  output_tokens?: number;
  input_tokens_cumulative?: number;
  output_tokens_cumulative?: number;
  cache_read_tokens?: number;
  cache_creation_tokens?: number;
  reasoning_tokens?: number;
}
export interface ToolCall {
  type?: "tool_call";
  payload?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ToolResult {
  type?: "tool_result";
  payload?: {
    /**
     * Globally-unique identifier shape: ULID (26 Crockford base32 chars, case-insensitive), hyphenated UUID (36 chars), or unhyphenated UUID (32 hex chars). Header ids, event ids, and envelope ids share this shape so cross-segment reconciliation can dedup by id (spec §8.5).
     */
    for_id?: string;
    ok: boolean;
    output?: string;
    truncated?: boolean;
    overflow_ref?: string | null;
    error?: string | null;
    /**
     * Structured per-toolkind outputs, keyed by the originating tool_call.tool. Optional; consumers fall back to payload.output when the relevant key is absent. Registered keys are writer-strict; unregistered/future toolkinds are opaque objects. Vendors extend a registered key via x-<vendor>/ pattern keys.
     */
    meta?: {
      mcp_call?: {
        content_blocks?: {
          type: "text" | "image" | "resource";
          text?: string;
          data?: string;
          mime_type?: string;
          uri?: string;
        }[];
        is_error?: boolean;
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^x-[a-z0-9]+(?:-[a-z0-9]+)*\/[a-z0-9][a-z0-9_-]*$".
         */
        [k: string]: unknown;
      };
      file_read?: {
        /**
         * @minItems 2
         * @maxItems 2
         */
        range?: [number, number];
        total_lines?: number;
        encoding?: string;
        truncated_at_line?: number | null;
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^x-[a-z0-9]+(?:-[a-z0-9]+)*\/[a-z0-9][a-z0-9_-]*$".
         */
        [k: string]: unknown;
      };
      shell_command?: {
        stdout?: string;
        stderr?: string;
        exit_code?: number | null;
        signal?: string | null;
        duration_ms?: number;
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^x-[a-z0-9]+(?:-[a-z0-9]+)*\/[a-z0-9][a-z0-9_-]*$".
         */
        [k: string]: unknown;
      };
      [k: string]: {
        [k: string]: unknown;
      };
    };
  };
  [k: string]: unknown;
}
export interface SessionSummary {
  type?: "session_summary";
  payload?: {
    scope: "session";
    text: string;
    model?: string;
  };
  [k: string]: unknown;
}
export interface SystemEvent {
  type?: "system_event";
  payload?: {
    /**
     * Lifecycle/hook signal category. Either one of the reserved cross-agent values, or an adapter-namespaced extension of the form `x-<adapter>/<name>` (lowercase, kebab-case adapter, snake/kebab name).
     */
    kind:
      | "session_start"
      | "session_end"
      | "turn_start"
      | "turn_end"
      | "subagent_start"
      | "subagent_end"
      | "pre_tool_use"
      | "post_tool_use"
      | "hook_fired"
      | "permission_request"
      | "permission_decision"
      | "permission_mode_change"
      | "cwd_change"
      | "env_snapshot"
      | "task_started"
      | "task_completed"
      | "plan_completed"
      | "turn_aborted"
      | "tool_decision"
      | "hook_progress"
      | "queue_operation"
      | "heartbeat"
      | "agent_error"
      | "agent_warning"
      | "api_error"
      | "stream_error"
      | "deprecation_notice"
      | "guardian_alert"
      | "model_rerouted"
      | "hook_failed"
      | `x-${string}/${string}`;
    text?: string;
    data?: {
      [k: string]: unknown;
    };
  };
  [k: string]: unknown;
}
export interface AgentThinking {
  type?: "agent_thinking";
  payload?: {
    text: string;
    model?: string;
    level?: "low" | "medium" | "high" | "xhigh";
  };
  [k: string]: unknown;
}
export interface UserInterrupt {
  type?: "user_interrupt";
  payload?: {
    reason?: string;
  };
  [k: string]: unknown;
}
export interface ContextCompact {
  type?: "context_compact";
  payload?: {
    summary: string;
    trigger?: "manual" | "auto";
    tokens_before?: number;
    tokens_after?: number;
  };
  [k: string]: unknown;
}
export interface BranchPoint {
  type?: "branch_point";
  payload?: {
    /**
     * Globally-unique identifier shape: ULID (26 Crockford base32 chars, case-insensitive), hyphenated UUID (36 chars), or unhyphenated UUID (32 hex chars). Header ids, event ids, and envelope ids share this shape so cross-segment reconciliation can dedup by id (spec §8.5).
     */
    from_id: string;
    reason?: string;
  };
  [k: string]: unknown;
}
export interface BranchSummary {
  type?: "branch_summary";
  payload?: {
    /**
     * Globally-unique identifier shape: ULID (26 Crockford base32 chars, case-insensitive), hyphenated UUID (36 chars), or unhyphenated UUID (32 hex chars). Header ids, event ids, and envelope ids share this shape so cross-segment reconciliation can dedup by id (spec §8.5).
     */
    abandoned_branch_id: string;
    summary: string;
    model?: string;
  };
  [k: string]: unknown;
}
export interface ModelChange {
  type?: "model_change";
  payload?: {
    from_model?: string;
    to_model: string;
  };
  [k: string]: unknown;
}
export interface SessionTerminated {
  type?: "session_terminated";
  payload?: {
    reason: "eof_with_open_tool_calls" | "process_terminated" | "truncated" | "user_abort";
    open_call_ids?: string[];
  };
  [k: string]: unknown;
}
export interface SessionEnd {
  type?: "session_end";
  payload?: {
    reason: "complete" | "user_quit" | "agent_idle";
    /**
     * Globally-unique identifier shape: ULID (26 Crockford base32 chars, case-insensitive), hyphenated UUID (36 chars), or unhyphenated UUID (32 hex chars). Header ids, event ids, and envelope ids share this shape so cross-segment reconciliation can dedup by id (spec §8.5).
     */
    final_message_id?: string;
  };
  [k: string]: unknown;
}
export interface CommandInvoke {
  type?: "command_invoke";
  payload?: {
    /**
     * User-visible identifier of the invoked capability. Leading slash for slash/builtin/custom_prompt commands (`/clear`); bare name for skills (`webapp-testing`).
     */
    name: string;
    /**
     * What kind of capability was invoked.
     */
    kind: "slash" | "builtin" | "skill" | "custom_prompt" | "plugin";
    /**
     * How the invocation reached the agent. `auto_trigger` covers description-matched skill activation with no user action; adapters MAY synthesize it (set source.synthesized=true).
     */
    via: "user_typed" | "auto_trigger" | "agent_invoked";
    args?: {
      [k: string]: unknown;
    };
    expansion_text?: string;
    /**
     * What the runtime did with the invocation. Either one of the reserved values, an adapter-namespaced extension of the form `x-<adapter>/<name>`, or null.
     */
    result_action?:
      | "compact"
      | "clear"
      | "expand"
      | "load_skill"
      | "noop"
      | `x-${string}/${string}`
      | null;
  };
  [k: string]: unknown;
}
/**
 * Catch-all for unrecognized event types. Readers must tolerate these.
 */
export interface Unknown {
  type?: string;
  payload?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
