/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecV0Dot1Dot0RouteImport } from './routes/spec/v0[.]1[.]0'
import { Route as SpecLatestRouteImport } from './routes/spec/latest'
import { Route as SchemaV0Dot1Dot0DotjsonRouteImport } from './routes/schema/v0[.]1[.]0[.]json'
import { Route as SchemaLatestDotjsonRouteImport } from './routes/schema/latest[.]json'
import { Route as ViewGistGistIdRouteImport } from './routes/view/gist/$gistId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecV0Dot1Dot0Route = SpecV0Dot1Dot0RouteImport.update({
  id: '/spec/v0.1.0',
  path: '/spec/v0.1.0',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecLatestRoute = SpecLatestRouteImport.update({
  id: '/spec/latest',
  path: '/spec/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaV0Dot1Dot0DotjsonRoute = SchemaV0Dot1Dot0DotjsonRouteImport.update({
  id: '/schema/v0.1.0.json',
  path: '/schema/v0.1.0.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaLatestDotjsonRoute = SchemaLatestDotjsonRouteImport.update({
  id: '/schema/latest.json',
  path: '/schema/latest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewGistGistIdRoute = ViewGistGistIdRouteImport.update({
  id: '/view/gist/$gistId',
  path: '/view/gist/$gistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/schema/latest.json': typeof SchemaLatestDotjsonRoute
  '/schema/v0.1.0.json': typeof SchemaV0Dot1Dot0DotjsonRoute
  '/spec/latest': typeof SpecLatestRoute
  '/spec/v0.1.0': typeof SpecV0Dot1Dot0Route
  '/view/gist/$gistId': typeof ViewGistGistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/schema/latest.json': typeof SchemaLatestDotjsonRoute
  '/schema/v0.1.0.json': typeof SchemaV0Dot1Dot0DotjsonRoute
  '/spec/latest': typeof SpecLatestRoute
  '/spec/v0.1.0': typeof SpecV0Dot1Dot0Route
  '/view/gist/$gistId': typeof ViewGistGistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/schema/latest.json': typeof SchemaLatestDotjsonRoute
  '/schema/v0.1.0.json': typeof SchemaV0Dot1Dot0DotjsonRoute
  '/spec/latest': typeof SpecLatestRoute
  '/spec/v0.1.0': typeof SpecV0Dot1Dot0Route
  '/view/gist/$gistId': typeof ViewGistGistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/schema/latest.json'
    | '/schema/v0.1.0.json'
    | '/spec/latest'
    | '/spec/v0.1.0'
    | '/view/gist/$gistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/schema/latest.json'
    | '/schema/v0.1.0.json'
    | '/spec/latest'
    | '/spec/v0.1.0'
    | '/view/gist/$gistId'
  id:
    | '__root__'
    | '/'
    | '/schema/latest.json'
    | '/schema/v0.1.0.json'
    | '/spec/latest'
    | '/spec/v0.1.0'
    | '/view/gist/$gistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchemaLatestDotjsonRoute: typeof SchemaLatestDotjsonRoute
  SchemaV0Dot1Dot0DotjsonRoute: typeof SchemaV0Dot1Dot0DotjsonRoute
  SpecLatestRoute: typeof SpecLatestRoute
  SpecV0Dot1Dot0Route: typeof SpecV0Dot1Dot0Route
  ViewGistGistIdRoute: typeof ViewGistGistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec/v0.1.0': {
      id: '/spec/v0.1.0'
      path: '/spec/v0.1.0'
      fullPath: '/spec/v0.1.0'
      preLoaderRoute: typeof SpecV0Dot1Dot0RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec/latest': {
      id: '/spec/latest'
      path: '/spec/latest'
      fullPath: '/spec/latest'
      preLoaderRoute: typeof SpecLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema/v0.1.0.json': {
      id: '/schema/v0.1.0.json'
      path: '/schema/v0.1.0.json'
      fullPath: '/schema/v0.1.0.json'
      preLoaderRoute: typeof SchemaV0Dot1Dot0DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema/latest.json': {
      id: '/schema/latest.json'
      path: '/schema/latest.json'
      fullPath: '/schema/latest.json'
      preLoaderRoute: typeof SchemaLatestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/gist/$gistId': {
      id: '/view/gist/$gistId'
      path: '/view/gist/$gistId'
      fullPath: '/view/gist/$gistId'
      preLoaderRoute: typeof ViewGistGistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchemaLatestDotjsonRoute: SchemaLatestDotjsonRoute,
  SchemaV0Dot1Dot0DotjsonRoute: SchemaV0Dot1Dot0DotjsonRoute,
  SpecLatestRoute: SpecLatestRoute,
  SpecV0Dot1Dot0Route: SpecV0Dot1Dot0Route,
  ViewGistGistIdRoute: ViewGistGistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
