import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const rootUrl = new URL("../", import.meta.url);
const schemaUrl = new URL("schema.json", rootUrl);
const outputUrl = new URL("packages/types/index.d.ts", rootUrl);
const checkOnly = process.argv.includes("--check");

const schema = JSON.parse(await readFile(schemaUrl, "utf8"));
const compiled = await compile(schema, "AgentTrailRecord", {
  bannerComment:
    "/*\n * Generated from schema.json by scripts/generate-types.ts.\n * Do not edit this file manually.\n */",
  style: {
    bracketSpacing: true,
    printWidth: 100,
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "all",
    useTabs: false,
  },
});

// json-schema-to-typescript lowers the `system_event.payload.kind` anyOf
// (reserved enum + adapter-namespaced pattern `^x-...$`) into
// `(reserved | { [k: string]: unknown }) & string`. The intersection erases
// the index-signature branch (`{ [k: string]: unknown } & string` is `never`),
// so TypeScript rejects valid extension kinds like `x-claudecode/diag`.
// Replace the whole block with a flat union of the reserved enum plus a
// template-literal type that matches the schema's `^x-...$` pattern.
const kindEnum = (
  schema as {
    $defs?: {
      events?: {
        system_event?: {
          properties?: {
            payload?: {
              properties?: {
                kind?: { anyOf?: Array<{ enum?: string[] }> };
              };
            };
          };
        };
      };
    };
  }
).$defs?.events?.system_event?.properties?.payload?.properties?.kind?.anyOf?.find((branch) =>
  Array.isArray(branch.enum),
)?.enum;
if (kindEnum === undefined || kindEnum.length === 0) {
  throw new Error(
    "generate-types: could not read reserved system_event.payload.kind enum from schema.",
  );
}
const KIND_BLOCK_RE =
  / {4}kind: \(\n {6}\| \(\n(?: {10}\| "[^"]+"\n)+ {8}\)\n {6}\| \{\n {10}\[k: string\]: unknown;\n {8}\}\n {4}\) &\n {6}string;/;
if (!KIND_BLOCK_RE.test(compiled)) {
  throw new Error(
    "generate-types: failed to locate the SystemEvent.payload.kind anyOf block to post-process; check json-schema-to-typescript output shape.",
  );
}
const flatUnion = [
  ...kindEnum.map((value) => `      | ${JSON.stringify(value)}`),
  "      | `x-$" + "{string}/$" + "{string}`",
].join("\n");
let generated = compiled.replace(KIND_BLOCK_RE, `    kind:\n${flatUnion};`);

const vcsTypeEnum = (
  schema as {
    $defs?: {
      vcs?: {
        properties?: {
          type?: { anyOf?: Array<{ enum?: string[] }> };
        };
      };
    };
  }
).$defs?.vcs?.properties?.type?.anyOf?.find((branch) => Array.isArray(branch.enum))?.enum;
if (vcsTypeEnum === undefined || vcsTypeEnum.length === 0) {
  throw new Error("generate-types: could not read reserved vcs.type enum from schema.");
}
const VCS_TYPE_RE = /export interface Vcs \{\n {2}type: \((?:"[^"]+"(?: \| )?)+\) \| string;/;
if (!VCS_TYPE_RE.test(generated)) {
  throw new Error(
    "generate-types: failed to locate the Vcs.type anyOf line to post-process; check json-schema-to-typescript output shape.",
  );
}
const vcsTypeReplacement = [
  ...vcsTypeEnum.map((value) => JSON.stringify(value)),
  "`x-$" + "{string}/$" + "{string}`",
].join(" | ");
generated = generated.replace(
  VCS_TYPE_RE,
  `export interface Vcs {\n  type: ${vcsTypeReplacement};`,
);

// json-schema-to-typescript collapses the `command_invoke.payload.result_action`
// oneOf pattern branch (`^x-...$`) into a bare `string`, widening the type so it
// accepts any string. Read the reserved enum from the schema and rewrite the
// generated line with the reserved literals, the template-literal extension type,
// and null — mirroring the system_event.kind handling above.
const resultActionEnum = (
  schema as {
    $defs?: {
      events?: {
        command_invoke?: {
          properties?: {
            payload?: {
              properties?: {
                result_action?: { oneOf?: Array<{ enum?: string[] }> };
              };
            };
          };
        };
      };
    };
  }
).$defs?.events?.command_invoke?.properties?.payload?.properties?.result_action?.oneOf?.find(
  (branch) => Array.isArray(branch.enum),
)?.enum;
if (resultActionEnum === undefined || resultActionEnum.length === 0) {
  throw new Error(
    "generate-types: could not read reserved command_invoke.payload.result_action enum from schema.",
  );
}
const RESULT_ACTION_RE = /( {4}result_action\?: )\((?:"[^"]+"(?: \| )?)+\) \| string \| null;/;
if (!RESULT_ACTION_RE.test(generated)) {
  throw new Error(
    "generate-types: failed to locate the CommandInvoke.payload.result_action line to post-process; check json-schema-to-typescript output shape.",
  );
}
const resultActionUnion = [
  ...resultActionEnum.map((value) => `      | ${JSON.stringify(value)}`),
  "      | `x-$" + "{string}/$" + "{string}`",
  "      | null",
].join("\n");
generated = generated.replace(RESULT_ACTION_RE, `    result_action?:\n${resultActionUnion};`);

const settingTriggerEnum = (
  schema as {
    $defs?: {
      events?: {
        model_change?: {
          properties?: {
            payload?: {
              properties?: {
                trigger?: { anyOf?: Array<{ enum?: string[] }> };
              };
            };
          };
        };
      };
    };
  }
).$defs?.events?.model_change?.properties?.payload?.properties?.trigger?.anyOf?.find((branch) =>
  Array.isArray(branch.enum),
)?.enum;
if (settingTriggerEnum === undefined || settingTriggerEnum.length === 0) {
  throw new Error("generate-types: could not read setting trigger enum from schema.");
}
const SETTING_TRIGGER_BLOCK_RE =
  / {4}trigger\?: \(\n {6}\| \("[^"]+"(?: \| "[^"]+")+\)\n {6}\| \{\n {10}\[k: string\]: unknown;\n {8}\}\n {4}\) &\n {6}string;/g;
const settingTriggerReplacement = [
  "    trigger?:",
  ...settingTriggerEnum.map((value) => `      | ${JSON.stringify(value)}`),
  "      | `x-$" + "{string}/$" + "{string}`;",
].join("\n");
const triggerMatchCount = generated.match(SETTING_TRIGGER_BLOCK_RE)?.length ?? 0;
if (triggerMatchCount !== 3) {
  throw new Error(
    `generate-types: expected 3 setting trigger anyOf blocks, found ${triggerMatchCount}; check json-schema-to-typescript output shape.`,
  );
}
generated = generated.replace(SETTING_TRIGGER_BLOCK_RE, settingTriggerReplacement);

const modeScopeEnum = (
  schema as {
    $defs?: {
      events?: {
        mode_change?: {
          properties?: {
            payload?: {
              properties?: {
                scope?: { anyOf?: Array<{ enum?: string[] }> };
              };
            };
          };
        };
      };
    };
  }
).$defs?.events?.mode_change?.properties?.payload?.properties?.scope?.anyOf?.find((branch) =>
  Array.isArray(branch.enum),
)?.enum;
if (modeScopeEnum === undefined || modeScopeEnum.length === 0) {
  throw new Error("generate-types: could not read mode_change.payload.scope enum from schema.");
}
const MODE_SCOPE_BLOCK_RE =
  / {4}scope: \(\n {6}\| \("[^"]+"(?: \| "[^"]+")+\)\n {6}\| \{\n {10}\[k: string\]: unknown;\n {8}\}\n {4}\) &\n {6}string;/;
if (!MODE_SCOPE_BLOCK_RE.test(generated)) {
  throw new Error(
    "generate-types: failed to locate the ModeChange.payload.scope anyOf block to post-process; check json-schema-to-typescript output shape.",
  );
}
const modeScopeReplacement = `    scope: ${[
  ...modeScopeEnum.map((value) => JSON.stringify(value)),
  "`x-$" + "{string}/$" + "{string}`",
].join(" | ")};`;
generated = generated.replace(MODE_SCOPE_BLOCK_RE, modeScopeReplacement);

const SESSION_METADATA_FIELD_RE =
  /(export interface SessionMetadataUpdate \{[\s\S]*?\| \{\n {8})field: string;(\n {8}value: unknown;[\s\S]*?\n {6}\};)/;
if (!SESSION_METADATA_FIELD_RE.test(generated)) {
  throw new Error(
    "generate-types: failed to locate the SessionMetadataUpdate vendor field line to post-process; check json-schema-to-typescript output shape.",
  );
}
generated = generated.replace(
  SESSION_METADATA_FIELD_RE,
  "$1field: `x-$" + "{string}/$" + "{string}`;$2",
);

// json-schema-to-typescript widens `tool_call.payload` to an index signature
// because the schema combines shared properties with many tool-specific `allOf`
// conditionals. Keep the public declaration aligned with the common
// writer-strict surface; tool-specific arg details remain validated by schema.
const TOOL_CALL_RE =
  /export interface ToolCall \{\n {2}type\?: "tool_call";\n {2}payload\?: \{\n {4}\[k: string\]: unknown;\n {2}\};\n {2}\[k: string\]: unknown;\n\}/;
if (!TOOL_CALL_RE.test(generated)) {
  throw new Error(
    "generate-types: failed to locate the ToolCall payload to post-process; check json-schema-to-typescript output shape.",
  );
}
generated = generated.replace(
  TOOL_CALL_RE,
  [
    "export interface ToolCall {",
    '  type?: "tool_call";',
    "  payload?: {",
    "    tool: ToolKind;",
    "    args: {",
    "      [k: string]: unknown;",
    "    };",
    "    usage?: AgentMessageUsage;",
    "    truncated?: boolean;",
    "    args_size?: number;",
    "    overflow_ref?: string | null;",
    "  };",
    "  [k: string]: unknown;",
    "}",
  ].join("\n"),
);

const toolCallAbortedScopeEnum = (
  schema as {
    $defs?: {
      events?: {
        tool_call_aborted?: {
          properties?: {
            payload?: {
              properties?: {
                scope?: { oneOf?: Array<{ enum?: string[] }> };
              };
            };
          };
        };
      };
    };
  }
).$defs?.events?.tool_call_aborted?.properties?.payload?.properties?.scope?.oneOf?.find((branch) =>
  Array.isArray(branch.enum),
)?.enum;
if (toolCallAbortedScopeEnum === undefined || toolCallAbortedScopeEnum.length === 0) {
  throw new Error(
    "generate-types: could not read tool_call_aborted.payload.scope enum from schema.",
  );
}
const toolCallAbortedReasonEnum = (
  schema as {
    $defs?: {
      events?: {
        tool_call_aborted?: {
          properties?: {
            payload?: {
              properties?: {
                reason?: { oneOf?: Array<{ enum?: string[] }> };
              };
            };
          };
        };
      };
    };
  }
).$defs?.events?.tool_call_aborted?.properties?.payload?.properties?.reason?.oneOf?.find((branch) =>
  Array.isArray(branch.enum),
)?.enum;
if (toolCallAbortedReasonEnum === undefined || toolCallAbortedReasonEnum.length === 0) {
  throw new Error(
    "generate-types: could not read tool_call_aborted.payload.reason enum from schema.",
  );
}
const TOOL_CALL_ABORTED_RE =
  /export interface ToolCallAborted \{\n {2}type\?: "tool_call_aborted";\n {2}payload\?: \{\n {4}\[k: string\]: unknown;\n {2}\};\n {2}\[k: string\]: unknown;\n\}/;
if (!TOOL_CALL_ABORTED_RE.test(generated)) {
  throw new Error(
    "generate-types: failed to locate the ToolCallAborted payload to post-process; check json-schema-to-typescript output shape.",
  );
}
const toolCallAbortedNonCallScope = [
  ...toolCallAbortedScopeEnum
    .filter((value) => value !== "tool_call")
    .map((value) => JSON.stringify(value)),
  "`x-$" + "{string}/$" + "{string}`",
].join(" | ");
const toolCallAbortedReasonLines = [
  ...toolCallAbortedReasonEnum.map((value) => `          | ${JSON.stringify(value)}`),
  "          | `x-$" + "{string}/$" + "{string}`",
];
const toolCallAbortedReason = [
  "        reason:",
  `${toolCallAbortedReasonLines.join("\n")};`,
  "        blocked_by?: string;",
  "        [k: string]: unknown;",
];
generated = generated.replace(
  TOOL_CALL_ABORTED_RE,
  [
    "export interface ToolCallAborted {",
    '  type?: "tool_call_aborted";',
    "  payload?:",
    "    | {",
    '        scope: "tool_call";',
    "        for_id: string;",
    `${toolCallAbortedReason.join("\n")}`,
    "      }",
    "    | {",
    `        scope: ${toolCallAbortedNonCallScope};`,
    "        for_id?: never;",
    `${toolCallAbortedReason.join("\n")}`,
    "      };",
    "  [k: string]: unknown;",
    "}",
  ].join("\n"),
);

// json-schema-to-typescript can mistake the `task_plan_update.payload.items`
// property name for the schema `items` keyword and leak `minItems?: 0` into the
// generated payload type. The schema has `additionalProperties:false`; this
// post-process keeps the public type aligned with writer-strict validation.
const TASK_PLAN_MIN_ITEMS_RE =
  /(export interface TaskPlanUpdate \{\n {2}type\?: "task_plan_update";\n {2}payload\?: \{\n(?: {4}[^\n]+\n)+?) {4}minItems\?: 0;\n/;
if (!TASK_PLAN_MIN_ITEMS_RE.test(generated)) {
  throw new Error(
    "generate-types: failed to locate the TaskPlanUpdate.payload.minItems artifact to post-process; check json-schema-to-typescript output shape.",
  );
}
generated = generated.replace(TASK_PLAN_MIN_ITEMS_RE, "$1");

// The schema expresses required-when-present usage counters with presence-only
// anyOf branches layered over `additionalProperties:false`. json-schema-to-
// typescript lowers those branches to `[k:string]: unknown`, which widens
// AgentMessageUsage and accepts fields the writer schema rejects. Rewrite this
// one public type to the exact structural contract from schema.json.
const AGENT_MESSAGE_USAGE_RE =
  /export type AgentMessageUsage = \([\s\S]*?\n {2}\) & \{\n(?: {4}[a-z_]+\?: number;\n)+ {2}\};/;
if (!AGENT_MESSAGE_USAGE_RE.test(generated)) {
  throw new Error(
    "generate-types: failed to locate the AgentMessageUsage anyOf block to post-process; check json-schema-to-typescript output shape.",
  );
}
generated = generated.replace(
  AGENT_MESSAGE_USAGE_RE,
  [
    "export type AgentMessageUsage = {",
    "  cache_read_tokens?: number;",
    "  cache_creation_tokens?: number;",
    "  reasoning_tokens?: number;",
    "  context_input_tokens?: number;",
    "  context_window_tokens?: number;",
    "} & (",
    "  | {",
    "      input_tokens: number;",
    "      input_tokens_cumulative?: number;",
    "    }",
    "  | {",
    "      input_tokens?: number;",
    "      input_tokens_cumulative: number;",
    "    }",
    ") &",
    "  (",
    "    | {",
    "        output_tokens: number;",
    "        output_tokens_cumulative?: number;",
    "      }",
    "    | {",
    "        output_tokens?: number;",
    "        output_tokens_cumulative: number;",
    "      }",
    "  );",
  ].join("\n"),
);

// json-schema-to-typescript lowers attachment uri|name anyOf branches to an
// index-signature union intersected with the base shape, which makes both uri
// and name appear required. Rewrite to the writer-strict structural contract.
const ATTACHMENT_RE =
  /export type Attachment = Attachment1 & \{[\s\S]*?\};\nexport type Attachment1 =[\s\S]*?\n {4}\};/;
if (!ATTACHMENT_RE.test(generated)) {
  throw new Error(
    "generate-types: failed to locate the Attachment anyOf block to post-process; check json-schema-to-typescript output shape.",
  );
}
generated = generated.replace(
  ATTACHMENT_RE,
  [
    "export type Attachment = {",
    '  kind: "image" | "file" | "other";',
    "  media_type?: string;",
    "} & (",
    "  | {",
    "      uri: string;",
    "      name?: string;",
    "    }",
    "  | {",
    "      name: string;",
    "      uri?: string;",
    "    }",
    ");",
  ].join("\n"),
);

if (checkOnly) {
  const existing = await readFile(outputUrl, "utf8").catch(() => "");

  if (existing !== generated) {
    console.error(`${fileURLToPath(outputUrl)} is stale. Run bun run generate:types.`);
    process.exit(1);
  }
} else {
  await writeFile(outputUrl, generated);
}
