import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const rootUrl = new URL("../", import.meta.url);
const schemaUrl = new URL("schema.json", rootUrl);
const outputUrl = new URL("packages/types/index.d.ts", rootUrl);
const checkOnly = process.argv.includes("--check");

const schema = JSON.parse(await readFile(schemaUrl, "utf8"));
const compiled = await compile(schema, "AgentTrailRecord", {
  bannerComment:
    "/*\n * Generated from schema.json by scripts/generate-types.ts.\n * Do not edit this file manually.\n */",
  style: {
    bracketSpacing: true,
    printWidth: 100,
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "all",
    useTabs: false,
  },
});

// json-schema-to-typescript lowers the `system_event.payload.kind` anyOf
// (reserved enum + adapter-namespaced pattern `^x-...$`) into
// `(reserved | { [k: string]: unknown }) & string`. The intersection erases
// the index-signature branch (`{ [k: string]: unknown } & string` is `never`),
// so TypeScript rejects valid extension kinds like `x-claudecode/diag`.
// Replace the whole block with a flat union of the reserved enum plus a
// template-literal type that matches the schema's `^x-...$` pattern.
const kindEnum = (
  schema as {
    $defs?: {
      events?: {
        system_event?: {
          properties?: {
            payload?: {
              properties?: {
                kind?: { anyOf?: Array<{ enum?: string[] }> };
              };
            };
          };
        };
      };
    };
  }
).$defs?.events?.system_event?.properties?.payload?.properties?.kind?.anyOf?.find((branch) =>
  Array.isArray(branch.enum),
)?.enum;
if (kindEnum === undefined || kindEnum.length === 0) {
  throw new Error(
    "generate-types: could not read reserved system_event.payload.kind enum from schema.",
  );
}
const KIND_BLOCK_RE =
  / {4}kind: \(\n {6}\| \(\n(?: {10}\| "[^"]+"\n)+ {8}\)\n {6}\| \{\n {10}\[k: string\]: unknown;\n {8}\}\n {4}\) &\n {6}string;/;
if (!KIND_BLOCK_RE.test(compiled)) {
  throw new Error(
    "generate-types: failed to locate the SystemEvent.payload.kind anyOf block to post-process; check json-schema-to-typescript output shape.",
  );
}
const flatUnion = [
  ...kindEnum.map((value) => `      | ${JSON.stringify(value)}`),
  "      | `x-${string}/${string}`",
].join("\n");
let generated = compiled.replace(KIND_BLOCK_RE, `    kind:\n${flatUnion};`);

// json-schema-to-typescript collapses the `command_invoke.payload.result_action`
// oneOf pattern branch (`^x-...$`) into a bare `string`, widening the type so it
// accepts any string. Read the reserved enum from the schema and rewrite the
// generated line with the reserved literals, the template-literal extension type,
// and null — mirroring the system_event.kind handling above.
const resultActionEnum = (
  schema as {
    $defs?: {
      events?: {
        command_invoke?: {
          properties?: {
            payload?: {
              properties?: {
                result_action?: { oneOf?: Array<{ enum?: string[] }> };
              };
            };
          };
        };
      };
    };
  }
).$defs?.events?.command_invoke?.properties?.payload?.properties?.result_action?.oneOf?.find(
  (branch) => Array.isArray(branch.enum),
)?.enum;
if (resultActionEnum === undefined || resultActionEnum.length === 0) {
  throw new Error(
    "generate-types: could not read reserved command_invoke.payload.result_action enum from schema.",
  );
}
const RESULT_ACTION_RE = /( {4}result_action\?: )\((?:"[^"]+"(?: \| )?)+\) \| string \| null;/;
if (!RESULT_ACTION_RE.test(generated)) {
  throw new Error(
    "generate-types: failed to locate the CommandInvoke.payload.result_action line to post-process; check json-schema-to-typescript output shape.",
  );
}
const resultActionUnion = [
  ...resultActionEnum.map((value) => `      | ${JSON.stringify(value)}`),
  "      | `x-${string}/${string}`",
  "      | null",
].join("\n");
generated = generated.replace(RESULT_ACTION_RE, `    result_action?:\n${resultActionUnion};`);

if (checkOnly) {
  const existing = await readFile(outputUrl, "utf8").catch(() => "");

  if (existing !== generated) {
    console.error(`${fileURLToPath(outputUrl)} is stale. Run bun run generate:types.`);
    process.exit(1);
  }
} else {
  await writeFile(outputUrl, generated);
}
